ignore_merge_commits = true

pre_bump_hooks = [
    "echo {{version}}",
]
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
]
[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "cocogitto_bot_playground"
owner = "cocogitto"

authors = [
    { username = "alisaitteke", signature = "Ali Sait Teke"}
]